### ISSUE TITLE
以dx后端编译失败

### ISSUE THREAD

**Issue by hanasaki666** [LuisaGroup/luisa-compute-rs#38]
我以dx后端编译path_tracer和vec_add案例都失败。

以下是编译错误：
```
PS D:\Projects\rust\luisa-compute-rs> cargo run --release --example vecadd -- dx
   Compiling luisa_compute_sys v0.1.1-alpha.1 (D:\Projects\rust\luisa-compute-rs\luisa_compute_sys)
error: failed to run custom build command for `luisa_compute_sys v0.1.1-alpha.1 (D:\Projects\rust\luisa-compute-rs\luisa_compute_sys)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\Projects\rust\luisa-compute-rs\target\release\build\luisa_compute_sys-616b67c2bebc77b6\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=./LuisaCompute/src/api
  cargo:rerun-if-changed=./LuisaCompute/src/ast
  cargo:rerun-if-changed=./LuisaCompute/src/backends
  cargo:rerun-if-changed=./LuisaCompute/src/core
  cargo:rerun-if-changed=./LuisaCompute/src/gui
  cargo:rerun-if-changed=./LuisaCompute/src/ir
  cargo:rerun-if-changed=./LuisaCompute/src/rust/luisa_compute_backend_impl
  cargo:rerun-if-changed=./LuisaCompute/src/rust/luisa_compute_ir
  cargo:rerun-if-changed=./LuisaCompute/src/rust/CMakeLists.txt
  cargo:rerun-if-changed=./LuisaCompute/src/py
  cargo:rerun-if-changed=./LuisaCompute/src/runtime
  cargo:rerun-if-changed=./LuisaCompute/src/vstl
  cargo:rerun-if-env-changed=CARGO_FEATURE_DX
  cargo:rerun-if-env-changed=CARGO_FEATURE_CPU
  cargo:rerun-if-env-changed=CARGO_FEATURE_REMOTE
  cargo:rerun-if-env-changed=CARGO_FEATURE_CUDA
  cargo:rerun-if-env-changed=CARGO_FEATURE_METAL
  cargo:rerun-if-env-changed=CARGO_FEATURE_PYTHON
  cargo:rerun-if-env-changed=CARGO_FEATURE_GUI
  cargo:rerun-if-env-changed=CARGO_FEATURE_OIDN
  cargo:rerun-if-env-changed=PROFILE
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\Projects\\rust\\luisa-compute-rs\\luisa_compute_sys\\./LuisaCompute" "-G" "Ninja" "-DLUISA_COMPUTE_ENABLE_DX=ON" "-DLUISA_COMPUTE_ENABLE_CPU=ON" "-DLUISA_COMPUTE_ENABLE_REMOTE=ON" "-DLUISA_COMPUTE_ENABLE_CUDA=ON" "-DLUISA_COMPUTE_ENABLE_METAL=ON" "-DLUISA_COMPUTE_ENABLE_PYTHON=OFF" "-DLUISA_COMPUTE_ENABLE_GUI=OFF" "-DLUISA_COMPUTE_DOWNLOAD_OIDN=OFF" "-DLUISA_COMPUTE_CHECK_BACKEND_DEPENDENCIES=ON" "-DLUISA_COMPUTE_BUILD_TESTS=OFF" "-DLUISA_COMPUTE_ENABLE_DSL=OFF" "-DLUISA_COMPUTE_ENABLE_RUST=ON" "-DCMAKE_INSTALL_PREFIX=D:\\Projects\\rust\\luisa-compute-rs\\target\\release\\build\\luisa_compute_sys-54f298cf8627f1ba\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_COMPILER=D:/VisualStudio/VS2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_COMPILER=D:/VisualStudio/VS2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_COMPILER=D:/VisualStudio/VS2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe" "-DCMAKE_BUILD_TYPE=Release"
  -- Enable Rust support (toolchain found at D:/rust/.cargo/bin/cargo.exe)
  -- IPO/LTO enabled for release builds
  -- Build spdlog: 1.13.0
  -- Build type: Release
  --
  -- Enable abort() calls on memory allocation failure (MI_XMALLOC=ON)
  -- Use the C++ compiler to compile (MI_USE_CXX=ON)
  --
  -- Library base name: mimalloc
  -- Version          : 2.1
  -- Build type       : release
  -- C++ Compiler     : D:/VisualStudio/VS2022/Enterprise/VC/Tools/MSVC/14.39.33519/bin/HostX64/x64/cl.exe
  -- Compiler flags   : /Zc:__cplusplus
  -- Compiler defines : MI_XMALLOC=1
  -- Link libraries   : psapi;shell32;user32;advapi32;bcrypt
  -- Build targets    : static
  --
  -- Build with DirectX backend
  -- DirectX SDK directory: OFF
  -- Downloading DirectX SDK from https://github.com/LuisaGroup/SDKs/releases/download/sdk/dx_sdk.zip
  -- Populating luisa_compute_dx_sdk
  -- Configuring done (0.1s)
  -- Generating done (0.0s)
  -- Build files have been written to: D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/_deps/luisa_compute_dx_sdk-subbuild
  ninja: no work to do.
  -- Build with CUDA backend: 12.4.99
  -- Could NOT find nvcomp (missing: nvcomp_DIR)
  -- Configuring done (3.7s)
  -- Generating done (0.2s)
  -- Build files have been written to: D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build
  running: "cmake" "--build" "." "--target" "luisa-compute-api" "--config" "Release" "--parallel" "8"
  [0/2] Re-checking globbed directories...
  [1/171] C:\WINDOWS\system32\cmd.exe /C "cd /D D:\Projects\rust\luisa-compute-rs\target\release\build\luisa_compute_sys-54f298cf8627f1ba\out\build\src\backends\dx && D:\cmake\bin\cmake.exe -E copy_directory D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/_deps/luisa_compute_dx_sdk-src D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/bin/"
  [2/171] Building Rust-dependent libraries...
  FAILED: src/rust/rust/release/luisa_compute_ir_static.lib src/rust/rust/release/luisa_compute_api_types.lib src/rust/rust/release/luisa_compute_backend_impl.dll src/rust/rust/release/luisa_compute_backend_impl.pdb src/rust/rust/release/luisa_compute_backend_impl.dll.lib D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/luisa_compute_ir_static.lib D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/luisa_compute_api_types.lib D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/luisa_compute_backend_impl.dll D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/luisa_compute_backend_impl.pdb D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/luisa_compute_backend_impl.dll.lib
  C:\WINDOWS\system32\cmd.exe /C "cd /D D:\Projects\rust\luisa-compute-rs\target\release\build\luisa_compute_sys-54f298cf8627f1ba\out\build\src\rust && D:\cmake\bin\cmake.exe -E env CARGO_TARGET_DIR=D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust EMBREE_DLL_OUT_DIR=D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust/release/embree CMAKE=D:/cmake/bin/cmake.exe CMAKE_GENERATOR=Ninja CMAKE_MAKE_PROGRAM=D:/ninja/ninja.exe -- D:/rust/.cargo/bin/cargo.exe build --manifest-path D:/Projects/rust/luisa-compute-rs/luisa_compute_sys/LuisaCompute/src/rust/Cargo.toml --profile release --no-default-features --features cpu,remote"
     Compiling embree_sys v0.1.9 (https://github.com/shiinamiyuki/embree-sys#76f45dbe)
  warning: unused import: `crate::*`
   --> luisa_compute_ir_v2\src\convert.rs:1:5
    |
  1 | use crate::*;
    |     ^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

  warning: unused variable: `module`
    --> luisa_compute_ir_v2\src\convert.rs:10:20
     |
  10 |     pub fn convert(module:ir_v1::ir::Module) {
     |                    ^^^^^^ help: if this is intentional, prefix it with an underscore: `_module`
     |
     = note: `#[warn(unused_variables)]` on by default

  warning: struct `V1ToV2` is never constructed
   --> luisa_compute_ir_v2\src\convert.rs:5:8
    |
  5 | struct V1ToV2 {
    |        ^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

  warning: associated function `convert` is never used
    --> luisa_compute_ir_v2\src\convert.rs:10:12
     |
  9  | impl V1ToV2 {
     | ----------- associated function in this implementation
  10 |     pub fn convert(module:ir_v1::ir::Module) {
     |            ^^^^^^^

  warning: `luisa_compute_ir_v2` (lib) generated 4 warnings (run `cargo fix --lib -p luisa_compute_ir_v2` to apply 2 suggestions)
  error: failed to run custom build command for `embree_sys v0.1.9 (https://github.com/shiinamiyuki/embree-sys#76f45dbe)`
  note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

  Caused by:
    process didn't exit successfully: `D:/Projects/rust/luisa-compute-rs/target/release/build/luisa_compute_sys-54f298cf8627f1ba/out/build/src/rust/rust\release\build\embree_sys-1b33491d44ef1c3c\build-script-build` (exit code: 101)
    --- stdout
    cargo:rerun-if-env-changed=EMBREE_ZIP_FILE
    cargo:rerun-if-env-changed=EMBREE_FORCE_BUILD_FROM_SOURCE

    --- stderr
    Downloading embree...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:44 --:--:--     0
    curl: (35) Recv failure: Connection was reset
    thread 'main' panicked at D:\rust\.cargo\git\checkouts\embree-sys-daf751a5f650b501\76f45db\build.rs:208:9:
    Unable to download embree
    stack backtrace:
       0:     0x7ff6670832b2 - std::sys_common::backtrace::_print::impl$0::fmt
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:44
       1:     0x7ff6670a66dd - core::fmt::rt::Argument::fmt
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\rt.rs:142
       2:     0x7ff6670a66dd - core::fmt::write
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\mod.rs:1120
       3:     0x7ff66707e5b1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\io\mod.rs:1846
       4:     0x7ff6670830da - std::sys_common::backtrace::_print
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:47
       5:     0x7ff6670830da - std::sys_common::backtrace::print
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:34
       6:     0x7ff667085799 - std::panicking::default_hook::closure$1
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:272
       7:     0x7ff667085455 - std::panicking::default_hook
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:292
       8:     0x7ff667085cb4 - std::panicking::rust_panic_with_hook
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:781
       9:     0x7ff667085b4b - std::panicking::begin_panic_handler::closure$0
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:651
      10:     0x7ff667083bb9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:171
      11:     0x7ff667085856 - std::panicking::begin_panic_handler
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:647
      12:     0x7ff6670aef57 - core::panicking::panic_fmt
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\panicking.rs:72
      13:     0x7ff666af6ee6 - <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next::h954691b192b6465a
      14:     0x7ff666af763a - <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next::h954691b192b6465a
      15:     0x7ff666af927a - <core::array::iter::IntoIter<T,_> as core::iter::traits::iterator::Iterator>::next::h954691b192b6465a
      16:     0x7ff666afaf66 - core::mem::forget::h81a7124bc03ed589
      17:     0x7ff666af9f79 - block_buffer::BlockBuffer<BlockSize,Kind>::digest_blocks::h4d2812e79a3706dc
      18:     0x7ff666afa87c - std::rt::lang_start::h289c8d5d5c3a3b10
      19:     0x7ff667079bf2 - std::rt::lang_start_internal::closure$2
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
      20:     0x7ff667079bf2 - std::panicking::try::do_call
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:554
      21:     0x7ff667079bf2 - std::panicking::try
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:518
      22:     0x7ff667079bf2 - std::panic::catch_unwind
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panic.rs:142
      23:     0x7ff667079bf2 - std::rt::lang_start_internal
                                   at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
      24:     0x7ff666afa857 - std::rt::lang_start::h289c8d5d5c3a3b10
      25:     0x7ff666af9339 - main
      26:     0x7ff6670ac8c0 - invoke_main
                                   at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
      27:     0x7ff6670ac8c0 - __scrt_common_main_seh
                                   at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
      28:     0x7ffd28527344 - BaseThreadInitThunk
      29:     0x7ffd29d026b1 - RtlUserThreadStart
  ninja: build stopped: subcommand failed.

  --- stderr
  CMake Warning at scripts/validate_options.cmake:47 (message):
    The Metal backend is not available.  The Metal backend will be disabled.
  Call Stack (most recent call first):
    scripts/validate_options.cmake:62 (report_feature_not_available)
    CMakeLists.txt:53 (include)


  CMake Deprecation Warning at src/ext/EASTL/packages/EABase/CMakeLists.txt:4 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Warning at src/backends/cuda/CMakeLists.txt:104 (message):
    nvCOMP not found.  The CUDA backend will be built without GPU compression
    support.  You may want to set the LUISA_COMPUTE_DOWNLOAD_NVCOMP option to
    ON to let LuisaCompute automatically download it.


  CMake Warning at src/backends/cuda/CMakeLists.txt:148 (message):
    NVTT not found! Please install NVTT from
    https://developer.nvidia.com/nvidia-texture-tools-exporter and set the
    CMake NVTT_DIR variable to the folder containing nvtt*.dll (e.g.
    C:\Program Files\NVIDIA Corporation\NVIDIA Texture Tools) .


  CMake Warning at src/backends/cuda/CMakeLists.txt:155 (message):
    NVTT_DIR didn't contain an NVTT shared library of the form nvtt*.dll or
    libnvtt.so.*! Is NVTT_DIR set correctly? NVTT_DIR was


  thread 'main' panicked at D:\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  stack backtrace:
     0:     0x7ff6ee6909a2 - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:44
     1:     0x7ff6ee6ae32d - core::fmt::rt::Argument::fmt
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\rt.rs:142
     2:     0x7ff6ee6ae32d - core::fmt::write
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\fmt\mod.rs:1120
     3:     0x7ff6ee68c1d1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\io\mod.rs:1846
     4:     0x7ff6ee6907ca - std::sys_common::backtrace::_print
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:47
     5:     0x7ff6ee6907ca - std::sys_common::backtrace::print
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:34
     6:     0x7ff6ee692e89 - std::panicking::default_hook::closure$1
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:272
     7:     0x7ff6ee692b45 - std::panicking::default_hook
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:292
     8:     0x7ff6ee6933a4 - std::panicking::rust_panic_with_hook
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:781
     9:     0x7ff6ee693279 - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:659
    10:     0x7ff6ee6912a9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\sys_common\backtrace.rs:171
    11:     0x7ff6ee692f46 - std::panicking::begin_panic_handler
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:647
    12:     0x7ff6ee6b3a27 - core::panicking::panic_fmt
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\core\src\panicking.rs:72
    13:     0x7ff6ee607057 - cmake::find_exe::{{closure}}::hf38d7fa6e68cae84
    14:     0x7ff6ee6068bb - <cmake::Version as core::default::Default>::default::h0757eb6fa37e269f
    15:     0x7ff6ee602f91 - cmake::Config::build::hcf56751cba1eecb3
    16:     0x7ff6ee5f36e9 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::he78e4901e3a370e5
    17:     0x7ff6ee5f61df - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::he78e4901e3a370e5
    18:     0x7ff6ee5f74e6 - core::fmt::Arguments::new_const::h2afb035d9c6fcafe
    19:     0x7ff6ee5f6339 - <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index::h20ebe5fc370ee87e
    20:     0x7ff6ee5f677c - std::rt::lang_start::h5e734069d029a711
    21:     0x7ff6ee687c72 - std::rt::lang_start_internal::closure$2
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
    22:     0x7ff6ee687c72 - std::panicking::try::do_call
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:554
    23:     0x7ff6ee687c72 - std::panicking::try
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panicking.rs:518
    24:     0x7ff6ee687c72 - std::panic::catch_unwind
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\panic.rs:142
    25:     0x7ff6ee687c72 - std::rt::lang_start_internal
                                 at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library\std\src\rt.rs:148
    26:     0x7ff6ee5f6757 - std::rt::lang_start::h5e734069d029a711
    27:     0x7ff6ee5f6239 - main
    28:     0x7ff6ee6b2470 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    29:     0x7ff6ee6b2470 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    30:     0x7ffd28527344 - BaseThreadInitThunk
    31:     0x7ffd29d026b1 - RtlUserThreadStart
```

**Comment by shiinamiyuki** [comment]
build script显示embree下载timeout了，如果不需要编译cpu后端可以在features里关掉，或者尝试解决网络问题。

**Comment by shiinamiyuki** [comment]
`cargo run --example xxx --no-default-features --features dx`

**Comment by shiinamiyuki** [comment]
看看你新的输出？难道dx后端也有下载问题？

**Comment by shiinamiyuki** [comment]
这是LuisaCompute主repo的cmake运行失败了，是否能提供cmake error log? 你能编译C++的LuisaCompute的repo吗？

**Comment by shiinamiyuki** [comment]
应该在`target/<profile>/luisa_compute_sys-<hash>/out/build/CMakeFiles` 下面，或者附近的地方，你搜下试试

**Comment by shiinamiyuki** [comment]
如果C++的repo也不能编译的话麻烦在 https://github.com/LuisaGroup/LuisaCompute 也开个issue,谢谢！

**Comment by 1216892614** [comment]
你要是输出太多了可以用 `>` 符号重映射到文本里慢慢看. 例如 `cargo run --example xxx --no-default-features --features dx > ./cmd.out`

**Comment by shiinamiyuki** [comment]
不是必须的，你不给参数就是默认使用cpu后端，你可以给dx为参数就行了
